apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountsdb
spec:
  selector:
    matchLabels:
      app: accountsdb
  template:
    metadata:
      labels:
        app: accountsdb
    spec:
      containers:
        - name: accountsdb
          image: yanny24211/soundsurfer:frontendWebApp
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: storage
              mountPath: /data/accountsdb
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: accountsdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: librarydb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librarydb
  template:
    metadata:
      labels:
        app: librarydb
    spec:
      containers:
        - name: librarydb
          image: yanny24211/soundsurfer:searchWebApp
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: searchWebApp:3306
            - name: kubeMQAddress
              value: 10.24.14.133:50000
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountdb
spec:
  selector:
    matchLabels:
      app:  accountdb
  template:
    metadata:
      labels:
        app: accountdb
    spec:
      containers:
        - name:  accountdb
          image: yanny24211/soundsurfer:generateWebApp
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: storage
              mountPath: /data/accountdb
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName:  accountdb-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: searchdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: searchdb
spec:
  selector:
    app: searchdb
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: librarydb
spec:
  selector:
    matchLabels:
      app: librarydb
  template:
    metadata:
      labels:
        app: librarydb
    spec:
      containers:
        - name: searchdb
          image: yanny24211/soundsurfer:librarydb
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: storage
              mountPath: /data/librarydb
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: librarydb-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: searchsong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searchsong
  template:
    metadata:
      labels:
        app: searchsong
    spec:
      containers:
        - name: searchsong
          image: yanny24211/soundsurfer:searchWebApp
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: librarydb:3306
            - name: kubeMQAddress
              value: 10.24.14.133:50000
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
