FROM mysql:8.3.0 

RUN alias uname='[ "$1" = "-m" ] && echo x86_64 || /bin/uname "$@"'

ENV MYSQL_DATABASE=Discover_LBS
ENV MYSQL_ROOT_PASSWORD=student123

COPY discover.sql /docker-entrypoint-initdb.d

EXPOSE 3306
